name: Test

on:
  workflow_dispatch: 
    inputs:
      filepaths:
        description: 'File paths'
        required: true
        default: |
          - 'test.txt'
          - 'test2.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          echo ${{ github.event.inputs.filepaths }}
