name: Test

on:
  - workflow_dispatch
  - push

jobs:
  generate-models:
    runs-on: ubuntu-latest
    steps:
    #"standard step" where repo needs to be checked-out first
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Generating models from my AsyncAPI document
      uses: asyncapi/github-action-for-cli@v3.1.1 # You can use any version you want
      with:
        command: generate
        filepath: asyncapi.yml
        language: golang
        parameters: --packageName=models
        output: docs/api/generated-models

    - name: Fix permissions
      run: sudo chown -R $USER:$USER .

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
